# Comprehensive Guide to Pandas Methods for Data Science

Welcome to this comprehensive reference guide for **Pandas**, the cornerstone library for data manipulation and analysis in Python. This notebook is designed to serve as both an educational walkthrough and a quick-reference sheet for data scientists.

### Contents:
1. **Introduction & Object Creation**: Series, DataFrames, and I/O.
2. **Viewing & Inspecting Data**: Understanding structure, shape, and quick statistics.
3. **Selection & Indexing**: Accessing columns, rows, and filtering.
4. **Data Cleaning & Missing Values**: Handling nulls, duplicates, and renaming.
5. **Sorting & Ordering**: Ordering indexes and values.
6. **Data Manipulation & Transformation**: Element-wise operations, mapping, string operations.
7. **Grouping & Aggregation**: Split-apply-combine paradigm.
8. **Combining & Merging DataFrames**: Merges, joins, and concatenation.
9. **Reshaping & Pivot Tables**: Reshaping data structures.
10. **Descriptive Statistics**: Statistical summaries, correlations, and cumulative operations.
11. **Time Series Analysis**: Datetime manipulation, resampling, and window calculations.

In [2]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')
print("Pandas version:", pd.__version__)
print("NumPy version:", np.__version__)

Pandas version: 3.0.2
NumPy version: 2.4.4

## 1. Introduction and Object Creation

Pandas has two primary data structures:
*   **Series**: A 1D labeled array capable of holding any data type.
*   **DataFrame**: A 2D labeled data structure with columns of potentially different types (like a table).

### Key Methods/Functions covered:
*   `pd.Series(data, index)`: Creates a 1D Series.
*   `pd.DataFrame(data, index, columns)`: Creates a 2D DataFrame.
*   `pd.read_csv()` / `to_csv()`: Reading/Writing CSV files.
*   `pd.read_json()` / `to_json()`: Reading/Writing JSON files.

In [3]:
# Creating a Series
series_data = [10, 20, 30, 40, 50]
labels = ['a', 'b', 'c', 'd', 'e']
s = pd.Series(data=series_data, index=labels)
print("Pandas Series:\n", s, "\n")

# Creating a DataFrame from a Dictionary
dict_data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 30, 35, 40],
    'Salary': [50000, 60000, 70000, 80000],
    'City': ['New York', 'Paris', 'London', 'Tokyo']
}
df = pd.DataFrame(data=dict_data)
print("Pandas DataFrame:\n", df)

# Simulating Writing and Reading CSV files
df.to_csv('sample_data.csv', index=False)
loaded_df = pd.read_csv('sample_data.csv')
print("\nLoaded from CSV:\n", loaded_df)

Pandas Series:
 a    10
b    20
c    30
d    40
e    50
dtype: int64

Pandas DataFrame:
       Name  Age  Salary      City
0    Alice   25   50000  New York
1      Bob   30   60000     Paris
2  Charlie   35   70000    London
3    David   40   80000     Tokyo

Loaded from CSV:
       Name  Age  Salary      City
0    Alice   25   50000  New York
1      Bob   30   60000     Paris
2  Charlie   35   70000    London
3    David   40   80000     Tokyo

## 2. Viewing and Inspecting Data

Before modeling or cleaning, you must inspect the data to understand its shape, columns, missingness, and types.

### Key Methods/Attributes covered:
*   `df.head(n)`: Returns the first `n` rows.
*   `df.tail(n)`: Returns the last `n` rows.
*   `df.sample(n)`: Returns a random sample of `n` rows.
*   `df.info()`: Prints a concise summary of the DataFrame (index, dtypes, non-null values, memory).
*   `df.describe()`: Generates descriptive statistics for numerical columns.
*   `df.shape`: Attribute returning `(rows, columns)`.
*   `df.dtypes`: Attribute returning the data type of each column.
*   `df.columns` / `df.index`: Access column headers and index labels.
*   `df.memory_usage()`: Returns memory usage of each column in bytes.

In [4]:
# Head, Tail, and Sample
print("Head (First 2 rows):")
display(df.head(2))

print("\nTail (Last 2 rows):")
display(df.tail(2))

print("\nSample (1 random row):")
display(df.sample(1))

# Inspecting characteristics
print("\nDataFrame Shape:", df.shape)
print("\nDataFrame dtypes:\n", df.dtypes)
print("\nDataFrame Columns:", df.columns.tolist())
print("\nDataFrame Index:", df.index)

# Info summary
print("\n--- DataFrame Info ---")
df.info()

# Summary statistics
print("\nDescriptive Statistics:")
display(df.describe())

# Memory Usage
print("\nMemory Usage (bytes):\n", df.memory_usage())

Head (First 2 rows):

    Name  Age  Salary      City
0  Alice   25   50000  New York
1    Bob   30   60000     Paris

Tail (Last 2 rows):

      Name  Age  Salary    City
2  Charlie   35   70000  London
3    David   40   80000   Tokyo

Sample (1 random row):

      Name  Age  Salary    City
2  Charlie   35   70000  London

DataFrame Shape: (4, 4)

DataFrame dtypes:
 Name        str
Age       int64
Salary    int64
City        str
dtype: object

DataFrame Columns: ['Name', 'Age', 'Salary', 'City']

DataFrame Index: RangeIndex(start=0, stop=4, step=1)

--- DataFrame Info ---
<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      str
 1   Age     4 non-null      int64
 2   Salary  4 non-null      int64
 3   City    4 non-null      str
dtypes: int64(2), str(2)
memory usage: 260.0 bytes

Descriptive Statistics:

             Age        Salary
count   4.000000      4.000000
mean   32.500000  65000.000000
std     6.454972  12909.944487
min    25.000000  50000.000000
25%    28.750000  57500.000000
50%    32.500000  65000.000000
75%    36.250000  72500.000000
max    40.000000  80000.000000

Memory Usage (bytes):
 Index     132
Name       32
Age        32
Salary     32
City       32
dtype: int64

## 3. Selection and Indexing

Selecting subsets of data is one of the most common tasks. Pandas provides label-based (`loc`) and integer-based (`iloc`) selection.

### Key Methods/Indexers covered:
*   `df['col_name']`: Column selection (returns a Series).
*   `df[['col1', 'col2']]`: Select multiple columns.
*   `df.loc[row_label, col_label]`: Access rows and columns by labels/boolean arrays.
*   `df.iloc[row_pos, col_pos]`: Access rows and columns by integer positions.
*   `df[df['col'] > val]`: Boolean indexing / filtering.
*   `df.query('expression')`: Filter rows using a query string.
*   `df.set_index('col')` / `df.reset_index()`: Set a column as index, or reset it.

In [5]:
# Selection by Column name
print("Select single column (Name):")
display(df['Name'])

# Selection using loc (label-based)
print("\nSelecting Alice and Bob (rows 0 and 1) with 'Name' and 'Salary' using .loc:")
display(df.loc[0:1, ['Name', 'Salary']])

# Selection using iloc (position-based)
print("\nSelecting first 2 rows and first 2 columns using .iloc:")
display(df.iloc[0:2, 0:2])

# Boolean indexing
print("\nFilter: Age > 30:")
display(df[df['Age'] > 30])

# Using .query()
print("\nFilter using query: City == 'New York' or Salary > 65000:")
display(df.query("City == 'New York' or Salary > 65000"))

# Setting and resetting index
print("\nSetting 'Name' as index:")
df_indexed = df.set_index('Name')
display(df_indexed)

print("\nResetting index back to default integers:")
display(df_indexed.reset_index())

Select single column (Name):

0      Alice
1        Bob
2    Charlie
3      David
Name: Name, dtype: str

Selecting Alice and Bob (rows 0 and 1) with 'Name' and 'Salary' using .loc:

    Name  Salary
0  Alice   50000
1    Bob   60000

Selecting first 2 rows and first 2 columns using .iloc:

    Name  Age
0  Alice   25
1    Bob   30

Filter: Age > 30:

      Name  Age  Salary    City
2  Charlie   35   70000  London
3    David   40   80000   Tokyo

Filter using query: City == 'New York' or Salary > 65000:

      Name  Age  Salary      City
0    Alice   25   50000  New York
2  Charlie   35   70000    London
3    David   40   80000     Tokyo

Setting 'Name' as index:

         Age  Salary      City
Name
Alice     25   50000  New York
Bob       30   60000     Paris
Charlie   35   70000    London
David     40   80000     Tokyo

Resetting index back to default integers:

      Name  Age  Salary      City
0    Alice   25   50000  New York
1      Bob   30   60000     Paris
2  Charlie   35   70000    London
3    David   40   80000     Tokyo

## 4. Data Cleaning and Handling Missing Values

Real-world datasets contain nulls, duplicates, and poorly formatted column names.

### Key Methods covered:
*   `df.isnull()` / `df.isna()`: Check for missing values (returns boolean DataFrame).
*   `df.notnull()`: Opposite of `isnull()`.
*   `df.dropna()`: Drops rows or columns containing missing values.
*   `df.fillna(value)`: Replaces missing values with a specified value.
*   `df.replace(old, new)`: Replaces specific values with other values.
*   `df.duplicated()`: Identifies duplicate rows.
*   `df.drop_duplicates()`: Removes duplicate rows.
*   `df.rename(columns={'old': 'new'})`: Renames columns or indexes.

In [5]:
# Let's create a DataFrame with missing values and duplicates
dirty_data = {
    'A': [1.0, 2.0, np.nan, 2.0, 1.0],
    'B': [np.nan, 5.0, 6.0, 5.0, np.nan],
    'C': ['cat', 'dog', 'cat', 'dog', 'cat']
}
df_dirty = pd.DataFrame(dirty_data)
print("Original Dirty DataFrame:")
display(df_dirty)

# Check for Null values
print("\nIsnull mapping:")
display(df_dirty.isnull())

print("\nNull counts per column:")
print(df_dirty.isnull().sum())

# Drop missing values
print("\nDropna (rows with any null):")
display(df_dirty.dropna())

# Fill missing values
print("\nFillna (fill nulls with 0 or mean):")
display(df_dirty.fillna({'A': df_dirty['A'].mean(), 'B': 0}))

# Replace a specific value
print("\nReplace 'cat' with 'feline':")
display(df_dirty.replace('cat', 'feline'))

# Duplicates handling
print("\nDuplicate row check:")
print(df_dirty.duplicated())

print("\nDataFrame after drop_duplicates:")
display(df_dirty.drop_duplicates())

# Rename columns
print("\nRenaming columns:")
display(df_dirty.rename(columns={'A': 'Alpha', 'B': 'Beta'}))

Original Dirty DataFrame:

     A    B    C
0  1.0  NaN  cat
1  2.0  5.0  dog
2  NaN  6.0  cat
3  2.0  5.0  dog
4  1.0  NaN  cat

Isnull mapping:

       A      B      C
0  False   True  False
1  False  False  False
2   True  False  False
3  False  False  False
4  False   True  False

Null counts per column:
A    1
B    2
C    0
dtype: int64

Dropna (rows with any null):

     A    B    C
1  2.0  5.0  dog
3  2.0  5.0  dog

Fillna (fill nulls with 0 or mean):

     A    B    C
0  1.0  0.0  cat
1  2.0  5.0  dog
2  1.5  6.0  cat
3  2.0  5.0  dog
4  1.0  0.0  cat

Replace 'cat' with 'feline':

     A    B       C
0  1.0  NaN  feline
1  2.0  5.0     dog
2  NaN  6.0  feline
3  2.0  5.0     dog
4  1.0  NaN  feline

Duplicate row check:
0    False
1    False
2    False
3     True
4     True
dtype: bool

DataFrame after drop_duplicates:

     A    B    C
0  1.0  NaN  cat
1  2.0  5.0  dog
2  NaN  6.0  cat

Renaming columns:

   Alpha  Beta    C
0    1.0   NaN  cat
1    2.0   5.0  dog
2    NaN   6.0  cat
3    2.0   5.0  dog
4    1.0   NaN  cat

## 5. Sorting and Ordering

### Key Methods covered:
*   `df.sort_values(by, ascending)`: Sorts the DataFrame by values in one or more columns.
*   `df.sort_index(ascending)`: Sorts the DataFrame by index labels.

In [6]:
# Sort by Salary descending
print("Sort by Salary (descending):")
display(df.sort_values(by='Salary', ascending=False))

# Sort by City ascending, then Age descending
print("\nSort by City (asc) then Age (desc):")
display(df.sort_values(by=['City', 'Age'], ascending=[True, False]))

# Sorting by index
print("\nSort by index (descending):")
display(df.sort_index(ascending=False))

Sort by Salary (descending):

      Name  Age  Salary      City
3    David   40   80000     Tokyo
2  Charlie   35   70000    London
1      Bob   30   60000     Paris
0    Alice   25   50000  New York

Sort by City (asc) then Age (desc):

      Name  Age  Salary      City
2  Charlie   35   70000    London
0    Alice   25   50000  New York
1      Bob   30   60000     Paris
3    David   40   80000     Tokyo

Sort by index (descending):

      Name  Age  Salary      City
3    David   40   80000     Tokyo
2  Charlie   35   70000    London
1      Bob   30   60000     Paris
0    Alice   25   50000  New York

## 6. Data Manipulation and Transformation

Transforming existing columns and applying custom functions.

### Key Methods/Attributes covered:
*   `df.apply(func, axis)`: Applies a function along an axis (rows or columns) of the DataFrame.
*   `df.applymap(func)` / `df.map(func)`: Applies a function element-wise across the entire DataFrame. (Note: `map` is used for element-wise on DataFrames in modern pandas, replacing `applymap`).
*   `series.map(arg)`: Maps values of a Series using input correspondence (dict, series, or function).
*   `df.astype(dtype)`: Casts a pandas object to a specified dtype.
*   `df.assign(new_col=...)`: Assigns new columns to a DataFrame (returns a new DataFrame).
*   `df.drop(labels, axis)`: Removes columns or rows.
*   `series.value_counts()`: Returns counts of unique values.
*   `series.unique()` / `series.nunique()`: Array of unique values and number of unique values.
*   `series.str`: String accessor containing methods like `contains()`, `lower()`, `upper()`, `split()`.

In [7]:
# Let's use apply to double the salaries
print("Using apply to double Salary:")
display(df['Salary'].apply(lambda x: x * 2))

# Map values in a series (e.g. City to country code)
city_map = {'New York': 'USA', 'Paris': 'FRA', 'London': 'GBR', 'Tokyo': 'JPN'}
print("\nMapping City to Country using series.map:")
display(df['City'].map(city_map))

# Change type using astype
print("\nCasting Age to float:")
display(df['Age'].astype(float))

# Adding a column using assign
print("\nAdding a Tax column:")
df_tax = df.assign(Tax = df['Salary'] * 0.15)
display(df_tax)

# Dropping columns
print("\nDropping City and Age:")
display(df.drop(columns=['City', 'Age']))

# Unique values and value counts
print("\nValue counts for City:")
print(df['City'].value_counts())

print("\nUnique cities:", df['City'].unique())
print("Number of unique cities:", df['City'].nunique())

# Using str accessor
print("\nString manipulation (lowercase Name):")
display(df['Name'].str.lower())

print("\nChecking if Name contains 'ar':")
display(df['Name'].str.contains('ar'))

Using apply to double Salary:

0    100000
1    120000
2    140000
3    160000
Name: Salary, dtype: int64

Mapping City to Country using series.map:

0    USA
1    FRA
2    GBR
3    JPN
Name: City, dtype: object

Casting Age to float:

0    25.0
1    30.0
2    35.0
3    40.0
Name: Age, dtype: float64

Adding a Tax column:

      Name  Age  Salary      City      Tax
0    Alice   25   50000  New York   7500.0
1      Bob   30   60000     Paris   9000.0
2  Charlie   35   70000    London  10500.0
3    David   40   80000     Tokyo  12000.0

Dropping City and Age:

      Name  Salary
0    Alice   50000
1      Bob   60000
2  Charlie   70000
3    David   80000

Value counts for City:
New York    1
Paris       1
London      1
Tokyo       1
Name: City, dtype: int64

Unique cities: ['New York' 'Paris' 'London' 'Tokyo']
Number of unique cities: 4

String manipulation (lowercase Name):

0      alice
1        bob
2    charlie
3      david
Name: Name, dtype: object

Checking if Name contains 'ar':

0    False
1    False
2     True
3    False
Name: Name, dtype: bool

## 7. Grouping and Aggregation

The "split-apply-combine" pattern allows you to segment datasets and analyze statistics across categories.

### Key Methods covered:
*   `df.groupby('col')`: Groups DataFrame by a column.
*   `groupby.agg(func)` or `groupby.aggregate(func)`: Compute aggregate statistics.
*   `groupby.mean()`, `groupby.sum()`, `groupby.count()`, `groupby.size()`: Shorthand aggregations.
*   `groupby.transform(func)`: Applies function to groups, returning a Series matching the original size.
*   `groupby.filter(func)`: Filters rows belonging to groups that satisfy a boolean condition.

In [8]:
# Create sample sales dataset
sales_data = {
    'Department': ['Electronics', 'Electronics', 'Clothing', 'Clothing', 'Electronics', 'Clothing'],
    'Store': ['Store_A', 'Store_B', 'Store_A', 'Store_B', 'Store_A', 'Store_A'],
    'Sales': [1200, 1500, 800, 600, 1100, 750],
    'Quantity': [12, 15, 8, 6, 11, 7]
}
df_sales = pd.DataFrame(sales_data)
print("Sales DataFrame:")
display(df_sales)

# Basic Groupby mean
print("\nMean Sales by Department:")
display(df_sales.groupby('Department')['Sales'].mean())

# Aggregation with multiple functions
print("\nMultiple Aggregations (sum, mean, max) on Sales and Quantity:")
display(df_sales.groupby('Department').agg({
    'Sales': ['sum', 'mean'],
    'Quantity': 'max'
}))

# Groupby transform (returns same shape as original)
print("\nStandardized Sales within each Department (using transform):")
mean_sales = df_sales.groupby('Department')['Sales'].transform('mean')
std_sales = df_sales.groupby('Department')['Sales'].transform('std')
df_sales['Sales_Z_Score'] = (df_sales['Sales'] - mean_sales) / std_sales
display(df_sales)

# Groupby filter (keep groups whose sum of Sales > 2000)
print("\nFiltering to keep only departments with total Sales > 2000:")
display(df_sales.groupby('Department').filter(lambda x: x['Sales'].sum() > 2000))

Sales DataFrame:

    Department    Store  Sales  Quantity
0  Electronics  Store_A   1200        12
1  Electronics  Store_B   1500        15
2     Clothing  Store_A    800         8
3     Clothing  Store_B    600         6
4  Electronics  Store_A   1100        11
5     Clothing  Store_A    750         7

Mean Sales by Department:

Department
Clothing        716.666667
Electronics    1266.666667
Name: Sales, dtype: float64

Multiple Aggregations (sum, mean, max) on Sales and Quantity:

            Sales              Quantity
              sum         mean      max
Department
Clothing     2150   716.666667        8
Electronics  3800  1266.666667       15

Standardized Sales within each Department (using transform):

    Department    Store  Sales  Quantity  Sales_Z_Score
0  Electronics  Store_A   1200        12      -0.320256
1  Electronics  Store_B   1500        15       1.120897
2     Clothing  Store_A    800         8       0.800641
3     Clothing  Store_B    600         6      -1.120897
4  Electronics  Store_A   1100        11      -0.800641
5     Clothing  Store_A    750         7       0.320256

Filtering to keep only departments with total Sales > 2000:

    Department    Store  Sales  Quantity  Sales_Z_Score
0  Electronics  Store_A   1200        12      -0.320256
1  Electronics  Store_B   1500        15       1.120897
2     Clothing  Store_A    800         8       0.800641
3     Clothing  Store_B    600         6      -1.120897
4  Electronics  Store_A   1100        11      -0.800641
5     Clothing  Store_A    750         7       0.320256

## 8. Combining and Merging DataFrames

Combining separate datasets using concatenation, SQL-like merges, and joins.

### Key Methods/Functions covered:
*   `pd.concat([df1, df2], axis)`: Appends DataFrames along rows (axis=0) or columns (axis=1).
*   `pd.merge(df1, df2, on, how)`: Database-style merge (Inner, Left, Right, Outer).
*   `df1.join(df2)`: Join on index (shorthand for merge).

In [9]:
# DataFrames for merging
df_emp = pd.DataFrame({
    'Emp_ID': [101, 102, 103, 104],
    'Name': ['Amy', 'Ben', 'Chris', 'David'],
    'Dept_ID': [1, 2, 1, 3]
})

df_dept = pd.DataFrame({
    'Dept_ID': [1, 2, 4],
    'Dept_Name': ['HR', 'IT', 'Marketing']
})

print("Employee DataFrame:")
display(df_emp)
print("Department DataFrame:")
display(df_dept)

# Merge (Inner Join)
print("\nInner Merge on Dept_ID:")
display(pd.merge(df_emp, df_dept, on='Dept_ID', how='inner'))

# Merge (Left Join)
print("\nLeft Merge on Dept_ID:")
display(pd.merge(df_emp, df_dept, on='Dept_ID', how='left'))

# Concatenation (axis=0: stacked vertically)
print("\nVertical concatenation of Employee DataFrames:")
df_emp_new = pd.DataFrame({'Emp_ID': [105], 'Name': ['Emma'], 'Dept_ID': [2]})
display(pd.concat([df_emp, df_emp_new], axis=0, ignore_index=True))

Employee DataFrame:

   Emp_ID   Name  Dept_ID
0     101    Amy        1
1     102    Ben        2
2     103  Chris        1
3     104  David        3

Department DataFrame:

   Dept_ID  Dept_Name
0        1         HR
1        2         IT
2        4  Marketing

Inner Merge on Dept_ID:

   Emp_ID   Name  Dept_ID Dept_Name
0     101    Amy        1        HR
1     103  Chris        1        HR
2     102    Ben        2        IT

Left Merge on Dept_ID:

   Emp_ID   Name  Dept_ID Dept_Name
0     101    Amy        1        HR
1     102    Ben        2        IT
2     103  Chris        1        HR
3     104  David        3       NaN

Vertical concatenation of Employee DataFrames:

   Emp_ID   Name  Dept_ID
0     101    Amy        1
1     102    Ben        2
2     103  Chris        1
3     104  David        3
4     105   Emma        2

## 10. Descriptive Statistics

Pandas provides a suite of math and statistical methods to summarize and evaluate data.

### Key Methods covered:
*   `df.mean()`, `df.median()`, `df.sum()`, `df.min()`, `df.max()`, `df.std()`, `df.var()`: Basic metrics.
*   `df.corr()` / `df.cov()`: Correlation and covariance matrices between numerical columns.
*   `df.cumsum()` / `df.cumprod()`: Cumulative sum and cumulative product.
*   `df.pct_change()`: Percentage change between successive elements.

In [11]:
# Basic math operations
stats_df = pd.DataFrame({
    'X': [10, 15, 20, 25, 30],
    'Y': [2, 4, 8, 16, 32]
})
print("Stats DataFrame:")
display(stats_df)

print("\nSums:\n", stats_df.sum())
print("\nMeans:\n", stats_df.mean())
print("\nMedians:\n", stats_df.median())

# Correlation Matrix
print("\nCorrelation Matrix:")
display(stats_df.corr())

# Cumulative sum
print("\nCumulative Sum of X:")
display(stats_df['X'].cumsum())

# Pct change
print("\nPercentage change in Y:")
display(stats_df['Y'].pct_change())

Stats DataFrame:

    X   Y
0  10   2
1  15   4
2  20   8
3  25  16
4  30  32

Sums:
 X    100
Y     62
dtype: int64

Means:
 X    20.0
Y    12.4
dtype: float64

Medians:
 X    20.0
Y     8.0
dtype: float64

Correlation Matrix:

          X         Y
X  1.000000  0.933257
Y  0.933257  1.000000

Cumulative Sum of X:

0     10
1     25
2     45
3     70
4    100
Name: X, dtype: int64

Percentage change in Y:

0    NaN
1    1.0
2    1.0
3    1.0
4    1.0
Name: Y, dtype: float64

In [13]:
import os
if os.path.exists('sample_data.csv'):
    os.remove('sample_data.csv')
    print("Cleaned up temporary CSV files successfully.")

Cleaned up temporary CSV files successfully.